title: National Archives of Singapore
title-abbreviated: NAS
description: The National Archives of Singapore (NAS) is the keeper of records
  of national or historical significance.
url: https://corporate.nas.gov.sg
google_analytics: UA-50447519-1
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
resources_name: media
paginate: 12
paginate_path: /media/page:num
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
favicon: /images/Logo/2_8_National_Archives_Singapore_Logo_RGB_FA.png
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
colors:
  primary-color: "#3A6222"
  secondary-color: "#946F00"
  media-colors:
    - title: media-color-one
      color: "#185E72"
    - title: media-color-two
      color: "#854266"
    - title: media-color-three
      color: "#9F2F1D"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
staging: https://staging.d1xnob5hpz6fv6.amplifyapp.com/
prod: https://master.d1xnob5hpz6fv6.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
shareicon: /images/Logo/2_8_National_Archives_Singapore_Logo_RGB_FA.png
is_government: false
facebook-pixel: ""
google_analytics_ga4: G-T70TZK8HJV
linkedin-insights: ""
